baseurl = "/"
title = "Kubernetes Security Training"

enableGitInfo = true

languageCode = "en-us"

contentDir = "content/en"

[minify]
disableSVG = true

# default content language
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[Languages]
[Languages.en]
title = "Kubernetes Basics Training"
languageName = "English"
weight = 1

# navigation
[Languages.en.menu]

[[Languages.en.menu.main]]
weight = 10
name = "songlaa gmbh"
url = "https://www.songlaa.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
  # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
  style = "tango"
  # Uncomment if you want your chosen highlight style used for code blocks without a specified language
  # guessSyntax = "true"

[[cascade]]
no_list = true

[params]
copyright = "acend gmbh"
github_repo = "https://github.com/songlaa/kubernetes-security-training"
github_branch = "main"

automaticSectionNumbers = true
enabledModule = "base cloudscale"
distroName = "Kubernetes"
cliToolName = "kubectl"
customer = "none"

[params.containerImages]
deployment-image-url = "quay.io/acend/example-web-go:latest"
training-image-url = "quay.io/acend/example-web-python:latest"
training-image-port = "5000"
training-image-probe-port = "5000"
nginxinc-nginx-unprivileged = "docker.io/nginxinc/nginx-unprivileged"
nginx = "docker.io/nginx:latest"
stress = "quay.io/acend/stress:latest"
busybox = "docker.io/busybox:1.28"

# Enable Lunr.js offline search
offlineSearch = true

[[params.replaceContent.placeholders]]
placeholder = "<namespace>"
queryParam = "n"
defaultValue = "$USER"

[[params.replaceContent.placeholders]]
placeholder = "<appdomain>"
queryParam = "a"
defaultValue = "<appdomain>"



[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to false to disable the About link in the site footer
footer_about_enable = false

############################## social links ##############################
[params.links]
[[params.links.developer]]
name = "GitHub"
icon = "fab fa-github"
url = "https://github.com/songlaa/kubernetes-security-training"


[[params.links.user]]
name = "LinkedIn"
icon = "fab fa-linkedin-in"
url = "https://linkedin.com/gabriel-graf-6b6446319/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.100.0"
  [[module.imports]]
    path = "github.com/acend/docsy-acend"
    disable = false
  [[module.imports]]
    path = "github.com/acend/docsy-plus"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false
