apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-secure
  labels:
    app: multi-container-example
spec:
  containers:
    - name: curl-container
      image: curlimages/curl
      command: ["sleep", "3600"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    - name: nginx-container
      image: nginxinc/nginx-unprivileged
      ports:
        - containerPort: 8080
          name: http
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        readOnlyRootFilesystem: false #nginx uses tmp files
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
# to call: kubectl exec -it multi-container-pod-secure -c curl-container -- curl localhost:8080
